image: Ubuntu2004

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - sudo curl -L "https://github.com/docker/compose/releases/download/v2.12.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo docker-compose up -d
  - sleep 60
  - java "-Dspring.datasource.url=jdbc:postgresql://localhost:5432/app" -jar ./artifacts/aqa-shop.jar &
  - sleep 60
  - chmod +x gradlew

build_script:
  - ./gradlew "-Ddb.url=jdbc:postgresql://localhost:5432/app" test --info -Dselenide.headless=true